name = "form-cf"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "form_db"
database_id = "d00a4582-02b8-461e-9d96-7360f2f965de"

[vars]
# Change this password to something secret and strong
ADMIN_BEARER = "change_me_very_secret_admin_token_123"
# Add allowed domains (comma separated)
ALLOWED_ORIGINS = "https://alghorani.me,https://cihrs.org,http://localhost:3000"
# Turnstile setup (optional) - get keys from Cloudflare dashboard
# TURNSTILE_SECRET_KEY = "your_turnstile_secret_key_here"
# Encryption keys (required) - don't change unless you know what you're doing
ENC_KEY_B64 = "O7Nrr0qEe+4UznoAwa+9HzUbw20I86eAET2pZmLUJvg="
ENC_KEY_ID = "default-key-2024"

# Production settings
[env.production]
vars = { ENVIRONMENT = "production" }

# Development settings
[env.development]
vars = { ENVIRONMENT = "development" }