name = "form-cf"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "form_db"
database_id = "d00a4582-02b8-461e-9d96-7360f2f965de"

[vars]
# غير كلمة المرور هذه لشيء سري وقوي
ADMIN_BEARER = "change_me_very_secret_admin_token_123"
# أضف النطاقات المسموحة (فاصلة بينها)
ALLOWED_ORIGINS = "https://alghorani.me,https://cihrs.org,http://localhost:3000"

# إعدادات الإنتاج
[env.production]
vars = { ENVIRONMENT = "production" }

# إعدادات التطوير
[env.development]
vars = { ENVIRONMENT = "development" }